services:
  strapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: limaudio-api
    ports:
      - '1337:1337'
    environment:
      - HOST=${HOST}
      - PORT=${PORT}
      - APP_KEYS=${APP_KEYS}
      - API_TOKEN_SALT=${API_TOKEN_SALT}
      - ADMIN_JWT_SECRET=${ADMIN_JWT_SECRET}
      - TRANSFER_TOKEN_SALT=${TRANSFER_TOKEN_SALT}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - DATABASE_CLIENT=${DATABASE_CLIENT}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_SSL=${DATABASE_SSL}
      - DATABASE_FILENAME=${DATABASE_FILENAME}
      - JWT_SECRET=${JWT_SECRET}
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_ACCESS_SECRET=${S3_ACCESS_SECRET}
      - S3_REGION=${S3_REGION}
      - S3_ENDPOINT={S3_ENDPOINT}
      - S3_BUCKET={S3_BUCKET}
    volumes:
      - .:/limaudio-api
      - /limaudio-api/node_modules
    restart: unless-stopped
  nginx:
    image: nginx:latest
    container_name: limaudio-nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - strapi
    restart: unless-stopped
